In [130]:
import pandas as pd

In [51]:
import pandas as pd

grid_id = 113

file_path = rf"C:\INCOiS\ARGO\DATA\South_Data\Grid_Parquet\grid_{grid_id}.parquet"

df = pd.read_parquet(file_path)

print(df.shape)
print(df.head())

(1376980, 17)
   GRID_ID          PROFILE            DATE        LON    LAT  TEMP_MIN  \
0      113  D1900158_063.nc  19500101000000  82.015999  0.192     7.147
1      113  D1900158_063.nc  19500101000000  82.015999  0.192     7.147
2      113  D1900158_063.nc  19500101000000  82.015999  0.192     7.147
3      113  D1900158_063.nc  19500101000000  82.015999  0.192     7.147
4      113  D1900158_063.nc  19500101000000  82.015999  0.192     7.147

    TEMP_MAX  TEMP_MEAN   PSAL_MIN   PSAL_MAX  PSAL_MEAN   PRES_MEAN  \
0  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
1  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
2  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
3  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
4  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396

        PRES       TEMP       PSAL TEMP_QC PSAL_QC
0   4.200000  29.011999  35.252998    b'1'    b'1'
1   9.300000  29.014000  35.252998    b'1'    b'1'
2  19.500000  29.033001  35.265999    b'1'    b'1'
3  28.799999  29.037001  35.275002    b'1'    b'1'
4  39.000000  28.882000  35.237000    b'1'    b'1'

In [53]:
df.columns

Index(['GRID_ID', 'PROFILE', 'DATE', 'LON', 'LAT', 'TEMP_MIN', 'TEMP_MAX',
       'TEMP_MEAN', 'PSAL_MIN', 'PSAL_MAX', 'PSAL_MEAN', 'PRES_MEAN', 'PRES',
       'TEMP', 'PSAL', 'TEMP_QC', 'PSAL_QC'],
      dtype='object')

In [55]:
df["TEMP_QC"] = (
    df["TEMP_QC"]
    .astype(str)
    .str.replace("b'", "", regex=False)
    .str.replace("'", "", regex=False)
)

df["PSAL_QC"] = (
    df["PSAL_QC"]
    .astype(str)
    .str.replace("b'", "", regex=False)
    .str.replace("'", "", regex=False)
)
df["DATE"] = pd.to_datetime(
    df["DATE"].astype(str),
    format="%Y%m%d%H%M%S",
    errors="coerce"
)

print(df[["DATE"]].head())
print(df.head(15))

        DATE
0 1950-01-01
1 1950-01-01
2 1950-01-01
3 1950-01-01
4 1950-01-01
    GRID_ID          PROFILE       DATE        LON    LAT  TEMP_MIN  \
0       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
1       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
2       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
3       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
4       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
5       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
6       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
7       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
8       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
9       113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
10      113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
11      113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
12      113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
13      113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
14      113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147

     TEMP_MAX  TEMP_MEAN   PSAL_MIN   PSAL_MAX  PSAL_MEAN   PRES_MEAN  \
0   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
1   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
2   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
3   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
4   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
5   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
6   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
7   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
8   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
9   29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
10  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
11  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
12  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
13  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
14  29.037001  15.193509  34.974998  35.412998  35.114449  315.780396

          PRES       TEMP       PSAL TEMP_QC PSAL_QC
0     4.200000  29.011999  35.252998       1       1
1     9.300000  29.014000  35.252998       1       1
2    19.500000  29.033001  35.265999       1       1
3    28.799999  29.037001  35.275002       1       1
4    39.000000  28.882000  35.237000       1       1
5    49.500000  28.752001  35.208000       1       1
6    59.400002  28.671000  35.227001       1       1
7    69.500000  28.243999  35.311001       1       1
8    79.800003  27.709000  35.362999       1       1
9    89.500000  26.308001  35.412998       1       1
10   99.099998  20.952000  35.266998       1       1
11  109.699997  19.962999  35.243999       1       1
12  119.099998  17.874001  35.178001       1       1
13  129.300003  16.908001  35.189999       1       1
14  139.600006  16.684999  35.189999       1       1

In [57]:
from seawater import dpth

df["DEPTH"] = dpth(
    df["PRES"].values,
    df["LAT"].values
)
print(df)

         GRID_ID          PROFILE       DATE        LON    LAT  TEMP_MIN  \
0            113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
1            113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
2            113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
3            113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
4            113  D1900158_063.nc 1950-01-01  82.015999  0.192     7.147
...          ...              ...        ...        ...    ...       ...
1376975      113  R7902408_005.nc 1950-01-01  81.733333  3.300     5.571
1376976      113  R7902408_005.nc 1950-01-01  81.733333  3.300     5.571
1376977      113  R7902408_005.nc 1950-01-01  81.733333  3.300     5.571
1376978      113  R7902408_005.nc 1950-01-01  81.733333  3.300     5.571
1376979      113  R7902408_005.nc 1950-01-01  81.733333  3.300     5.571

          TEMP_MAX  TEMP_MEAN   PSAL_MIN   PSAL_MAX  PSAL_MEAN   PRES_MEAN  \
0        29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
1        29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
2        29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
3        29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
4        29.037001  15.193509  34.974998  35.412998  35.114449  315.780396
...            ...        ...        ...        ...        ...         ...
1376975  30.375000  15.401507  34.758999  35.154999  34.976593  462.873993
1376976  30.375000  15.401507  34.758999  35.154999  34.976593  462.873993
1376977  30.375000  15.401507  34.758999  35.154999  34.976593  462.873993
1376978  30.375000  15.401507  34.758999  35.154999  34.976593  462.873993
1376979  30.375000  15.401507  34.758999  35.154999  34.976593  462.873993

                PRES       TEMP       PSAL TEMP_QC PSAL_QC        DEPTH
0           4.200000  29.011999  35.252998       1       1     4.176884
1           9.300000  29.014000  35.252998       1       1     9.248702
2          19.500000  29.033001  35.265999       1       1    19.391959
3          28.799999  29.037001  35.275002       1       1    28.639785
4          39.000000  28.882000  35.237000       1       1    38.782083
...              ...        ...        ...     ...     ...          ...
1376975  1162.900024   5.951000  34.916000       1       1  1153.265283
1376976  1188.500000   5.806000  34.910999       1       1  1178.581413
1376977  1213.000000   5.711000  34.909000       1       1  1202.806904
1376978  1237.699951   5.644000  34.908001       1       1  1227.227275
1376979  1262.599976   5.571000  34.904999       1       1  1251.842581

[1376980 rows x 18 columns]

In [59]:
import numpy as np
import pandas as pd

bins = [0, 50,200, 500, 1000, 2000, 6000]
labels = ["0-50", "50-200", "200-500", "500-1000", "1000-2000", "2000-6000"]

df["DEPTH_BIN"] = pd.cut(df["DEPTH"], bins=bins, labels=labels, include_lowest=True)

In [61]:
df["TEMP_Z"] = df.groupby("DEPTH_BIN")["TEMP"].transform(
    lambda x: (x - x.mean()) / x.std()
)

C:\Users\skaki\AppData\Local\Temp\ipykernel_1900\307516810.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df["TEMP_Z"] = df.groupby("DEPTH_BIN")["TEMP"].transform(

In [63]:
df["PSAL_Z"] = df.groupby("DEPTH_BIN")["PSAL"].transform(
    lambda x: (x - x.mean()) / x.std()
)

C:\Users\skaki\AppData\Local\Temp\ipykernel_1900\277221917.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df["PSAL_Z"] = df.groupby("DEPTH_BIN")["PSAL"].transform(

In [65]:

df["YEAR"] = df["DATE"].dt.year
df["MONTH"] = df["DATE"].dt.month
df["DAY"] = df["DATE"].dt.day
df["SEASON"] = (df["MONTH"] % 12 + 3) // 3
df.head()

,GRID_ID,PROFILE,DATE,LON,LAT,TEMP_MIN,TEMP_MAX,TEMP_MEAN,PSAL_MIN,PSAL_MAX,...,TEMP_QC,PSAL_QC,DEPTH,DEPTH_BIN,TEMP_Z,PSAL_Z,YEAR,MONTH,DAY,SEASON
0,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,1,4.176884,0-50,-0.123454,0.475372,1950,1,1,1
1,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,1,9.248702,0-50,-0.120986,0.475372,1950,1,1,1
2,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,1,19.391959,0-50,-0.097545,0.477070,1950,1,1,1
3,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,1,28.639785,0-50,-0.092611,0.478247,1950,1,1,1
4,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,1,38.782083,0-50,-0.283831,0.473281,1950,1,1,1

In [67]:
season_map = {
    1: "Winter",
    2: "Spring",
    3: "Summer",
    4: "Autumn"
}

df["SEASON_NAME"] = df["SEASON"].map(season_map)
df.head()

,GRID_ID,PROFILE,DATE,LON,LAT,TEMP_MIN,TEMP_MAX,TEMP_MEAN,PSAL_MIN,PSAL_MAX,...,PSAL_QC,DEPTH,DEPTH_BIN,TEMP_Z,PSAL_Z,YEAR,MONTH,DAY,SEASON,SEASON_NAME
0,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,4.176884,0-50,-0.123454,0.475372,1950,1,1,1,Winter
1,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,9.248702,0-50,-0.120986,0.475372,1950,1,1,1,Winter
2,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,19.391959,0-50,-0.097545,0.477070,1950,1,1,1,Winter
3,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,28.639785,0-50,-0.092611,0.478247,1950,1,1,1,Winter
4,113,D1900158_063.nc,1950-01-01,82.015999,0.192,7.147,29.037001,15.193509,34.974998,35.412998,...,1,38.782083,0-50,-0.283831,0.473281,1950,1,1,1,Winter

In [69]:
def apply_zscore_flags(df):
    """
    Convert Z-scores into QC flags.
    """
    print("\n--- STEP 7: APPLYING Z-SCORE FLAGS ---")

    def zscore_to_flag(z):
        if pd.isna(z):
            return 9
        abs_z = abs(z)
        if abs_z <= 2.0:
            return 1
        elif abs_z <= 3.0:
            return 2
        elif abs_z <= 4.0:
            return 3
        else:
            return 4

    # Apply flags
    print("Applying temperature Z-score flags...")
    df['TEMP_Z_FLAG'] = df['TEMP_Z'].apply(zscore_to_flag)

    print("Applying salinity Z-score flags...")
    df['PSAL_Z_FLAG'] = df['PSAL_Z'].apply(zscore_to_flag)

    # Final flag = worst of temp and sal
    df['Z_FINAL_FLAG'] = df[['TEMP_Z_FLAG', 'PSAL_Z_FLAG']].max(axis=1)

    # Add human readable label
    flag_labels = {
        1: 'GOOD',
        2: 'PROBABLY_GOOD',
        3: 'PROBABLY_BAD',
        4: 'BAD',
        9: 'MISSING'
    }
    df['Z_FLAG_LABEL'] = df['Z_FINAL_FLAG'].map(flag_labels)

    # Print distributions

    print(f"\nFinal Z-flag distribution:")
    for flag, count in df['Z_FINAL_FLAG'].value_counts().sort_index().items():
        label = flag_labels[flag]
        pct = 100 * count / len(df)
        print(f" Flag {flag} ({label:15s}): {count:>12,} ({pct:.2f}%)")

    print("\n✅ Z-score flags applied")

    return df
df = apply_zscore_flags(df)

--- STEP 7: APPLYING Z-SCORE FLAGS ---
Applying temperature Z-score flags...
Applying salinity Z-score flags...

Final Z-flag distribution:
 Flag 1 (GOOD           ):    1,259,001 (91.43%)
 Flag 2 (PROBABLY_GOOD  ):       64,224 (4.66%)
 Flag 3 (PROBABLY_BAD   ):       35,281 (2.56%)
 Flag 4 (BAD            ):       18,473 (1.34%)
 Flag 9 (MISSING        ):            1 (0.00%)

✅ Z-score flags applied

In [70]:
df.columns

Index(['GRID_ID', 'PROFILE', 'DATE', 'LON', 'LAT', 'TEMP_MIN', 'TEMP_MAX',
       'TEMP_MEAN', 'PSAL_MIN', 'PSAL_MAX', 'PSAL_MEAN', 'PRES_MEAN', 'PRES',
       'TEMP', 'PSAL', 'TEMP_QC', 'PSAL_QC', 'DEPTH', 'DEPTH_BIN', 'TEMP_Z',
       'PSAL_Z', 'YEAR', 'MONTH', 'DAY', 'SEASON', 'SEASON_NAME',
       'TEMP_Z_FLAG', 'PSAL_Z_FLAG', 'Z_FINAL_FLAG', 'Z_FLAG_LABEL'],
      dtype='object')

In [73]:
import os

output_folder = r"C:\INCOiS\ARGO\DATA\South_Data\Preprocessed_Grid_Parquet"
os.makedirs(output_folder, exist_ok=True)

output_file = os.path.join(output_folder, "Grid_360.parquet")

df.to_parquet(
    output_file,
    engine="pyarrow",
    compression="snappy",
    index=False
)

print("Saved successfully!")
print(output_file)

Saved successfully!
C:\INCOiS\ARGO\DATA\South_Data\Preprocessed_Grid_Parquet\Grid_360.parquet

In [74]:
df_check = pd.read_parquet(output_file)

print(df_check.columns)
print(df_check[["PRES", "DEPTH", "DEPTH_BIN"]].head())

Index(['GRID_ID', 'PROFILE', 'DATE', 'LON', 'LAT', 'TEMP_MIN', 'TEMP_MAX',
       'TEMP_MEAN', 'PSAL_MIN', 'PSAL_MAX', 'PSAL_MEAN', 'PRES_MEAN', 'PRES',
       'TEMP', 'PSAL', 'TEMP_QC', 'PSAL_QC', 'DEPTH', 'DEPTH_BIN', 'TEMP_Z',
       'PSAL_Z', 'YEAR', 'MONTH', 'DAY', 'SEASON', 'SEASON_NAME',
       'TEMP_Z_FLAG', 'PSAL_Z_FLAG', 'Z_FINAL_FLAG', 'Z_FLAG_LABEL'],
      dtype='object')
        PRES      DEPTH DEPTH_BIN
0   4.200000   4.176884      0-50
1   9.300000   9.248702      0-50
2  19.500000  19.391959      0-50
3  28.799999  28.639785      0-50
4  39.000000  38.782083      0-50

In [ ]:
import pandas as pd

# Read the preprocessed parquet file
df = pd.read_parquet(
    r"C:\INCOiS\ARGO\DATA\South_Data\Preprocessed_Grid_Parquet\Grid_360.parquet"
)

# Save as CSV
output_file = r"C:\INCOiS\ARGO\DATA\South_Data\CSV_FOLDER\Grid_360.csv"

df.to_csv(output_file, index=False)

print("CSV saved successfully!")
print(output_file)

In [281]:
import os

# Grid folders
grid_folder = r"C:\INCOiS\ARGO\DATA\South_Data"

folder_grids = {
    int(name.split("_")[1])
    for name in os.listdir(grid_folder)
    if name.startswith("grid_") and os.path.isdir(os.path.join(grid_folder, name))
}

# CSV files
csv_folder = r"C:\INCOiS\ARGO\DATA\South_Data\CSV_FOLDER"

csv_grids = {
    int(name.replace("Grid_", "").replace(".csv", ""))
    for name in os.listdir(csv_folder)
    if name.startswith("Grid_") and name.endswith(".csv")
}

missing = sorted(folder_grids - csv_grids)

print("Number of missing grids:", len(missing))
print("Missing grids:", missing)

Number of missing grids: 1
Missing grids: [72]